### ISSUE TITLE
I can not install the requirements. I got the following error while installing :

### ISSUE THREAD

**Issue by Shubhamverma2796** [zinmyoswe/Django-Ecommerce#15]
![Screenshot (445)](https://user-images.githubusercontent.com/54266411/94715354-fb273700-036a-11eb-8744-8a2adfffc561.png)

**Comment by 7saikat7** [comment]
install that particular file  differently

**Comment by RiswanBasha** [comment]
did you finished this project

**Comment by 7saikat7** [comment]
I don't get you sorry!
I don't have any repo named that!  So please provide me link or something .
Thank you!

**Comment by linusaltacc** [comment]
Update requirements with new versions.

Make sure to Download and Install Postgresql for your OS before installing packages with pip.

[New requirements.txt](https://github.com/zinmyoswe/Django-Ecommerce/blob/8960c1b81e8fa667d5886bd65df4e71d259df8b3/requirements.txt)

**Comment by zenpeaky** [comment]
@Shubhamverma2796  Update zope.interface to 5.4.0 will fix your issue, or just download @linusaltacc requirements file
